[package]
name = "compositor-ffi"
version = "1.7.0"
edition = "2021"

[dependencies]
compositor = { path = "../compositor" }
compositor-skia = { path = "../compositor-skia" }
value-box = "1.0"
reference-box = "1.0"
string-box = "1.1"
array-box = "1.0"