[package]
name = "compositor-ffi"
version = "2.2.0"
edition = "2021"

[dependencies]
compositor = { path = "../compositor" }
reference-box = "1.1"
string-box = "1.1"
array-box = "1.0"
value-box = { version = "2", features = [ "phlow" ] }