[package]
name = "compositor-skia-ffi"
version = "2.2.0"
edition = "2021"

[dependencies]
compositor = { path = "../compositor" }
compositor-skia = { path = "../compositor-skia" }
value-box = { version = "2" }
reference-box = "1.1"