[package]
name = "compositor-skia-ffi"
version = "2.0.0"
edition = "2021"

[dependencies]
compositor = { path = "../compositor" }
compositor-skia = { path = "../compositor-skia" }
value-box = { version = "2", features = [ "phlow" ] }
reference-box = "1.0"