[package]
name = "compositor-skia-ffi"
version = "1.6.0"
edition = "2021"

[dependencies]
compositor = { path = "../compositor" }
compositor-skia = { path = "../compositor-skia" }
boxer = { git = "https://github.com/feenkcom/gtoolkit-boxer", rev = "fdc253f9559acd60e777b0357ec9d6efeff86577" }
